from fpdf import FPDF
import datetime

class MedicalReportPDF(FPDF):
    def header(self):
        # Medical Blue Header Banner
        self.set_fill_color(41, 128, 185)  # #2980b9
        self.rect(0, 0, 210, 35, 'F')
        
        # Title
        self.set_y(10)
        self.set_text_color(255, 255, 255)
        self.set_font('Arial', 'B', 20)
        self.cell(0, 10, 'MEDICAL DIAGNOSIS REPORT', 0, 1, 'C')
        
        # Subtitle
        self.set_font('Arial', '', 10)
        self.cell(0, 6, 'Fuzzy Decision Support System', 0, 1, 'C')
        self.ln(20)

    def footer(self):
        self.set_y(-20)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 5, 'CONFIDENTIAL: Generated by Fuzzy Decision Support System. For clinical reference only.', 0, 1, 'C')
        self.cell(0, 5, f'Page {self.page_no()}', 0, 0, 'C')

def generate_pdf_report(patient_name, patient_id, disease_module, inputs, result, doctor_name, notes=""):
    pdf = MedicalReportPDF()
    pdf.set_auto_page_break(auto=True, margin=25)
    pdf.add_page()
    
    # --- Report Metadata ---
    pdf.set_font("Arial", '', 10)
    pdf.set_text_color(100, 100, 100)
    report_date = datetime.datetime.now().strftime('%d %B %Y, %H:%M')
    pdf.cell(0, 6, f"Date Generated: {report_date}", 0, 1, 'R')
    pdf.ln(5)
    
    # --- Patient Information Section ---
    pdf.set_font('Arial', 'B', 12)
    pdf.set_fill_color(230, 240, 250)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, "  PATIENT INFORMATION", 0, 1, 'L', fill=True)
    pdf.ln(4)
    
    col_width = 40
    data_width = 100
    
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(col_width, 8, "Patient Name:", 0, 0)
    pdf.set_font("Arial", '', 11)
    pdf.cell(data_width, 8, str(patient_name), 0, 1)
    
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(col_width, 8, "Patient ID:", 0, 0)
    pdf.set_font("Arial", '', 11)
    pdf.cell(data_width, 8, str(patient_id), 0, 1)
    pdf.ln(5)
    
    # --- Diagnosis Result Section ---
    pdf.set_font('Arial', 'B', 12)
    pdf.set_fill_color(230, 240, 250)
    pdf.cell(0, 8, f"  CLINICAL ASSESSMENT ({disease_module.upper()})", 0, 1, 'L', fill=True)
    pdf.ln(4)
    
    risk_level = str(result.get('risk_level', 'Unknown')).upper()
    try:
        risk_percent = float(result.get('risk_percentage', 0))
    except:
        risk_percent = 0

    # Risk Color Coding
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(40, 10, "Risk Level:", 0, 0)
    
    # Determine Color
    if risk_percent < 35: 
        pdf.set_text_color(39, 174, 96) # Green
    elif risk_percent < 65:
        pdf.set_text_color(243, 156, 18) # Orange
    else:
        pdf.set_text_color(192, 57, 43) # Red

    pdf.set_font("Arial", 'B', 14)
    pdf.cell(50, 10, f"{risk_level} ({risk_percent}%)", 0, 1)
    
    # Reset color
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)
    
    # --- Clinical Inputs Section ---
    pdf.set_font('Arial', 'B', 12)
    pdf.set_fill_color(230, 240, 250)
    pdf.cell(0, 8, "  CLINICAL INPUTS & VITALS", 0, 1, 'L', fill=True)
    pdf.ln(4)
    
    # Draw a table with borders
    line_height = 8
    key_col_width = 90
    val_col_width = 60
    
    # Table Header
    pdf.set_fill_color(245, 245, 245)
    pdf.set_font("Arial", 'B', 10)
    pdf.cell(key_col_width, line_height, "  Parameter", 1, 0, 'L', fill=True)
    pdf.cell(val_col_width, line_height, "  Recorded Value", 1, 1, 'L', fill=True)
    
    # Table Content
    pdf.set_font("Arial", '', 10)
    
    def clean_key(k):
        return k.replace('_', ' ').title().replace("Input ", "")

    fill = False
    for key, value in inputs.items():
        if isinstance(value, (dict, list)): continue # Skip complex data for summary
        
        pdf.cell(key_col_width, line_height, f"  {clean_key(str(key))}", 1, 0, 'L', fill=fill)
        pdf.cell(val_col_width, line_height, f"  {str(value)}", 1, 1, 'L', fill=fill)
        # fill = not fill # Alternate row colors if desired (remove comment to enable)
    
    pdf.ln(8)

    # --- Doctor Notes Section ---
    if notes:
        pdf.set_font('Arial', 'B', 12)
        pdf.set_fill_color(230, 240, 250)
        pdf.cell(0, 8, "  PHYSICIAN NOTES", 0, 1, 'L', fill=True)
        pdf.ln(4)
        
        pdf.set_font("Arial", '', 11)
        pdf.multi_cell(0, 6, notes)
        pdf.ln(10)
    
    # --- Signature Section ---
    # Draw signature box at bottom
    pdf.set_y(-50) 
    pdf.set_text_color(0, 0, 0)
    pdf.line(10, pdf.get_y(), 80, pdf.get_y()) # Draw line
    pdf.ln(2)
    pdf.set_font("Arial", 'B', 10)
    pdf.cell(80, 5, f"Dr. {doctor_name}", 0, 1)
    pdf.set_font("Arial", '', 10)
    pdf.cell(80, 5, "Attending Physician", 0, 1)

    # Return PDF as bytes
    return pdf.output(dest='S').encode('latin-1')
